[tool.poetry]
name = "pyserv"
version = "0.1.0"
description = ""
authors = ["Dale <dale@farpoint.co.nz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
